"use client";

import React, { useState, useEffect } from "react";
import { useRouter, usePathname } from "next/navigation";
import {
  Settings,
  ChevronUp,
  ChevronDown,
  UserCheck,
  Play,
  RotateCcw,
  CheckSquare,
  Activity,
  AlertTriangle,
  MessageSquare
} from "lucide-react";

interface ControlRoomProps {
  currentUser: {
    fullName: string;
    role: string;
    email: string;
  };
}

export default function ReviewerControlRoom({ currentUser }: ControlRoomProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [activeTab, setActiveTab] = useState<"roles" | "tour" | "sim">("roles");
  const [simulating, setSimulating] = useState<string | null>(null);
  const [checklist, setChecklist] = useState<Record<string, boolean>>({});
  const router = useRouter();
  const pathname = usePathname();

  // Load checklist progress from local storage
  useEffect(() => {
    const saved = localStorage.getItem("muryaruwa_demo_tour");
    if (saved) {
      try {
        setChecklist(JSON.parse(saved));
      } catch (e) {
        // Ignore
      }
    }
  }, []);

  const saveChecklist = (updated: Record<string, boolean>) => {
    setChecklist(updated);
    localStorage.setItem("muryaruwa_demo_tour", JSON.stringify(updated));
  };

  const handleToggleCheck = (key: string) => {
    const updated = { ...checklist, [key]: !checklist[key] };
    saveChecklist(updated);
  };

  const handleRoleSwitch = async (roleName: string) => {
    setSimulating(`switching-${roleName}`);
    try {
      const res = await fetch("/api/auth/switch-role", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ role: roleName }),
      });

      if (res.ok) {
        router.refresh();
        setTimeout(() => {
          window.location.reload();
        }, 200);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setSimulating(null);
    }
  };

  const handleTriggerSim = async (action: string) => {
    setSimulating(action);
    try {
      let res;
      if (action === "missed-visit") {
        res = await fetch("/api/missed-visits", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            womanId: "seed-woman-id",
            visitType: "OTP",
            expectedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            reasonForMissedVisit: "Generated by demo simulator",
          }),
        });
      } else if (action === "responses") {
        res = await fetch("/api/messages/simulate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
        });
      } else if (action === "safeguarding") {
        res = await fetch("/api/women/opt-out", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ type: "SAFE_CONTACT_CONCERN" }),
        });
      } else if (action === "reset") {
        res = await fetch("/api/admin/reset-seeds", {
          method: "POST",
        });
      }

      if (res && res.ok) {
        alert(`Simulation successful for: ${action}`);
        router.refresh();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setSimulating(null);
    }
  };

  const tourSteps = [
    { key: "context", title: "Step 1: Problem Context", path: "/dashboard", desc: "Start dashboard walk & view initial metrics" },
    { key: "enrol", title: "Step 2: Enrol Participant", path: "/women/new", desc: "Try enrolling a new caregiver with Coded Name option" },
    { key: "safe", title: "Step 3: Safe Contact Check", path: "/women/new", desc: "Select Neutral Only / Mobilizer contact preference" },
    { key: "risk", title: "Step 4: Nutrition Risk screening", path: "/women/new", desc: "Try inputting low MUAC and observe recommended triggers" },
    { key: "referral", title: "Step 5: Referral tracking rules", path: "/referrals", desc: "Attempt to close an identified referral" },
    { key: "message", title: "Step 6: Voice Message sandboxing", path: "/messages", desc: "Review simulated message logs queues" },
    { key: "reports", title: "Step 7: CSV reporting data", path: "/reports", desc: "Verify export files capability" },
  ];

  const roles = [
    { code: "ADMIN", label: "System Admin" },
    { code: "SUPERVISOR", label: "FRAD Supervisor" },
    { code: "CHEW", label: "CHEW Muna" },
    { code: "MIDWIFE", label: "Midwife Muna" },
    { code: "MOBILIZER", label: "Mobilizer Jere" },
    { code: "PHC_BOARD_VIEWER", label: "PHC Board Reviewer" },
  ];

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col items-end">
      {/* Toggle Button */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-800 text-white font-semibold hover:bg-slate-700 shadow-lg transition-all cursor-pointer text-xs"
      >
        <Settings className="w-4 h-4 text-slate-700" />
        <span>Demo Controls</span>
        {isOpen ? <ChevronDown className="w-3.5 h-3.5" /> : <ChevronUp className="w-3.5 h-3.5" />}
      </button>

      {/* Expanded Dashboard Panel */}
      {isOpen && (
        <div className="w-80 sm:w-96 rounded-2xl bg-white border border-slate-200 mt-3 shadow-xl p-5 overflow-hidden animate-fade-in text-slate-800 flex flex-col max-h-[500px]">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div className="flex items-center gap-2 text-slate-800 font-bold text-xs uppercase tracking-wide">
              <UserCheck className="w-4 h-4 text-emerald-600" />
              <span>Reviewer Mode Tools</span>
            </div>
            <span className="text-[9px] bg-slate-100 border border-slate-200 px-2 py-0.5 rounded text-slate-600 font-bold font-mono">
              ROLE: {currentUser.role}
            </span>
          </div>

          {/* Current User Brief */}
          <div className="py-2.5 px-3 rounded-xl bg-slate-50 border border-slate-100 mt-3 text-xs flex justify-between items-center">
            <div>
              <p className="font-bold text-slate-800">{currentUser.fullName}</p>
              <p className="text-slate-500 mt-0.5">{currentUser.email}</p>
            </div>
          </div>

          {/* Tab Navigation */}
          <div className="grid grid-cols-3 gap-1 bg-slate-50 p-1 rounded-xl mt-3 text-[11px] font-semibold text-center border border-slate-100">
            <button
              onClick={() => setActiveTab("roles")}
              className={`py-1.5 rounded-lg cursor-pointer transition-all ${
                activeTab === "roles" ? "bg-slate-800 text-white shadow-sm" : "text-slate-500 hover:text-slate-800"
              }`}
            >
              Role Swapper
            </button>
            <button
              onClick={() => setActiveTab("tour")}
              className={`py-1.5 rounded-lg cursor-pointer transition-all ${
                activeTab === "tour" ? "bg-slate-800 text-white shadow-sm" : "text-slate-500 hover:text-slate-800"
              }`}
            >
              Walkthrough
            </button>
            <button
              onClick={() => setActiveTab("sim")}
              className={`py-1.5 rounded-lg cursor-pointer transition-all ${
                activeTab === "sim" ? "bg-slate-800 text-white shadow-sm" : "text-slate-500 hover:text-slate-800"
              }`}
            >
              Simulators
            </button>
          </div>

          {/* Tab Content Box */}
          <div className="flex-1 overflow-y-auto mt-4 pr-1 space-y-3 scrollbar-thin">
            {activeTab === "roles" && (
              <div className="space-y-2">
                <p className="text-[10px] text-slate-500 font-semibold leading-relaxed">
                  Toggle roles to view custom dashboards and permission controls:
                </p>
                <div className="grid grid-cols-2 gap-2 pt-1">
                  {roles.map((r) => {
                    const isActive = currentUser.role === r.code;
                    return (
                      <button
                        key={r.code}
                        disabled={isActive || simulating !== null}
                        onClick={() => handleRoleSwitch(r.code)}
                        className={`flex items-center gap-1.5 p-2 rounded-xl text-left text-xs transition-all border font-semibold ${
                          isActive
                            ? "bg-emerald-50 border-emerald-500 text-emerald-700 cursor-default"
                            : "bg-white border-slate-200 hover:border-slate-350 hover:bg-slate-50 text-slate-700 cursor-pointer active:scale-95"
                        } disabled:opacity-60`}
                      >
                        <UserCheck className={`w-3.5 h-3.5 flex-shrink-0 ${isActive ? "text-emerald-600" : "text-slate-600"}`} />
                        <span className="truncate">{r.label}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {activeTab === "tour" && (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <p className="text-[10px] text-slate-500 font-semibold">Walkthrough script guide:</p>
                  <button
                    onClick={() => saveChecklist({})}
                    className="text-[9px] text-slate-600 font-bold hover:underline flex items-center gap-1 cursor-pointer"
                  >
                    <RotateCcw className="w-2.5 h-2.5" /> Reset
                  </button>
                </div>

                <div className="space-y-1.5 pt-1">
                  {tourSteps.map((stepItem) => {
                    const isCompleted = checklist[stepItem.key];
                    const isCurrentPath = pathname === stepItem.path;

                    return (
                      <div
                        key={stepItem.key}
                        className={`p-2.5 rounded-xl border transition-all flex items-start justify-between gap-3 ${
                          isCurrentPath
                            ? "bg-slate-50 border-slate-300"
                            : "bg-white border-slate-200"
                        }`}
                      >
                        <div className="flex items-start gap-2.5">
                          <button
                            onClick={() => handleToggleCheck(stepItem.key)}
                            className="mt-0.5 focus:outline-none cursor-pointer"
                          >
                            <CheckSquare
                              className={`w-4 h-4 transition-colors ${
                                isCompleted ? "text-slate-800 fill-slate-800/5" : "text-slate-600"
                              }`}
                            />
                          </button>
                          <div>
                            <div className="flex items-center gap-1.5">
                              <span className={`text-xs font-bold ${isCompleted ? "line-through text-slate-450" : "text-slate-800"}`}>
                                {stepItem.title}
                              </span>
                              {isCurrentPath && (
                                <span className="text-[8px] font-bold text-emerald-800 bg-emerald-100 border border-emerald-200 px-1 rounded uppercase">
                                  Current
                                </span>
                              )}
                            </div>
                            <p className="text-[10px] text-slate-500 mt-0.5 leading-relaxed">
                              {stepItem.desc}
                            </p>
                          </div>
                        </div>

                        {stepItem.path && !isCurrentPath && (
                          <button
                            onClick={() => router.push(stepItem.path)}
                            className="text-[9px] text-slate-600 font-bold hover:underline uppercase flex-shrink-0 cursor-pointer pt-0.5"
                          >
                            Go
                          </button>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {activeTab === "sim" && (
              <div className="space-y-2">
                <p className="text-[10px] text-slate-500 font-semibold">
                  Trigger mock data background processes:
                </p>

                <div className="space-y-2 pt-1">
                  {/* Trigger SMS Responses */}
                  <button
                    disabled={simulating !== null}
                    onClick={() => handleTriggerSim("responses")}
                    className="w-full flex items-center justify-between p-2.5 rounded-xl bg-white border border-slate-200 hover:bg-slate-50 text-left transition-all active:scale-[0.99] cursor-pointer"
                  >
                    <div className="flex items-center gap-2">
                      <MessageSquare className="w-4 h-4 text-emerald-600" />
                      <div>
                        <p className="text-xs font-bold text-slate-800">Simulate Response SMS Logs</p>
                        <p className="text-[9px] text-slate-500 mt-0.5">Mock replies from mothers</p>
                      </div>
                    </div>
                    <Play className="w-3.5 h-3.5 text-slate-600" />
                  </button>

                  {/* Seed Resetter */}
                  <button
                    disabled={simulating !== null}
                    onClick={() => handleTriggerSim("reset")}
                    className="w-full flex items-center justify-between p-2.5 rounded-xl bg-white border border-slate-200 hover:bg-red-50/50 hover:border-red-200 text-left transition-all active:scale-[0.99] cursor-pointer"
                  >
                    <div className="flex items-center gap-2">
                      <RotateCcw className="w-4 h-4 text-red-700" />
                      <div>
                        <p className="text-xs font-bold text-slate-800">Reset Database Seed Data</p>
                        <p className="text-[9px] text-slate-500 mt-0.5">Clean database and restore seeds</p>
                      </div>
                    </div>
                    <Play className="w-3.5 h-3.5 text-slate-600" />
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
